language: android
jdk: openjdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.3
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository
git:
  submodules: false
before_install:
- chmod +x gradlew
script:
- "./gradlew assembleDebug"