language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - tools
  - build-tools-27.0.2
  - android-27
  - extra-android-m2repository
  - extra-android-support
  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- yes | sdkmanager "platforms;android-27"
- rm -f gradle.properties
- chmod +x gradlew
script:
- "./gradlew assembleRelease"
