language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.3
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
git:
  submodules: false
before_install:
- chmod +x gradlew
script:
- "./gradlew assembleDebug"